export const translateTag = (tag: string) => {
  const map = new Map([
    ["2.5 kg", {tag: 'weight',name:"2.5kg", handle:''}],
    ["5 kg",   {tag: "weight",name:"5kg", handle:''}],
    ["500 g",  {tag: "weight",name:"500g", handle:''}],
    ["Accessoires DIY", {tag:"collection",name:"Accessories DIY", handle:''}],
    ["Earth Matters",   {tag:"collection",name:"Earth Matters", handle:''}],
    ["Farbe Blau", {tag: "color", name: "blue", handle:''}],
    ["Farbe Braun", {tag: "color", name: "brown", handle:''}],
    ["Farbe Bronze",{tag: "color", name:  "bronze", handle:''}],
    ["Farbe Gelb",  {tag: "color", name: "yellow", handle:''}],
    ["Farbe Gold",  {tag: "color", name: "gold", handle:''}],
    ["Farbe Grau",  {tag: "color", name: "gray", handle:''}],
    ["Farbe Grün",  {tag: "color", name: "green", handle:''}],
    ["Farbe Lila",  {tag: "color", name: "purple", handle:''}],
    ["Farbe Natur", {tag: "color", name: "nature", handle:''}],
    ["Farbe Orange",{tag: "color", name: "orange", handle:''}],
    ["Farbe Rosa",  {tag: "color", name: "pink", handle:''}],
    ["Farbe Rot",   {tag: "color", name: "red", handle:''}],
    ['Farbe Schwarz', {tag:"color",name:"black", handle:''}],
    ['Farbe Silber',{tag:"color",name:"silver", handle:''}],
    ['Farbe Weiß',  {tag:"color",name:"white", handle:''}],
    ['Holland',     {tag:"collection", name:"Holland", handle:''}],
    ['Kiara',       {tag:"tag", name:"kiara", handle:''}],
    ['Kranz',       {tag:"tag", name:"wreath", handle:''}],
    ['NEU',         {tag:"collection",name:"NEW", handle:''}],
    ['Pampas',      {tag:"tag",name:"pampas"}],
    ['Pastell',     {tag:"tag",name:"Pastel"}],
    ['Rosenbox DIY',{tag:"collection",name:"Rose box DIY"}],
    ['Sommer 2023', {tag:"collection",name:"Summer 2023"}],
    ['Stabilisierte Rosen 1 cm',  {tag:"height",name:"1 cm"}],
    ['Stabilisierte Rosen 2 cm',  {tag:"height",name:"2 cm"}],
    ['Stabilisierte Rosen 3 cm',  {tag:"height",name:"3 cm"}],
    ['Stabilisierte Rosen 4 cm',  {tag:"height",name:"4 cm"}],
    ['Stabilisierte Rosen 5 cm',  {tag:"height",name:"5 cm"}],
    ['Stabilisierte Rosen 6 cm',  {tag:"height",name:"6 cm"}],
    ['Stabilisierte Rosen 7-8 cm',{tag:"height",name:"7-8 cm"}],
    ['Stem', {tag:"tag", name:"stem"}],
    ['X-mas', {tag:"collection",name:"Christmas"}],
  ]);
  return map.get(tag);
};
